app:
  port: 8194
  debug: True
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 60
python_path: /opt/python/bin/python3
python_lib_path: # 重要 python 依赖所在安装路径
  - "/opt/python/lib/python3.14"
  - "/usr/lib/x86_64-linux-gnu"
  - "/usr/lib/aarch64-linux-gnu"
  - "/etc/ssl/certs/ca-certificates.crt"
  - "/etc/nsswitch.conf"
  - "/etc/hosts"
  - "/etc/resolv.conf"
  - "/run/systemd/resolve/stub-resolv.conf"
  - "/run/resolvconf/resolv.conf"
  - "/etc/localtime"
  - "/usr/share/zoneinfo"
  - "/etc/timezone"
  - "/opt/python/lib/python3.14/site-packages/pandas"
enable_network: True # please make sure there is no network risk in your environment
enable_preload: False # please keep it as False for security purposes
log_path: "./logs" # path to store log files, default is "./logs"
nodejs_path: /usr/local/bin/node
allowed_syscalls: 
proxy:
  socks5: ''
  http: ''
  https: ''
